### PR TITLE
support gnome 3.30

### PR DESCRIPTION
**Pull request by jimmytheneutrino**
See #197 for the issue. 
Adapted as proposed by @smcv .
This contains just the bare minimum to support gnome 3.30. I did not modify any version info.

### CODE REVIEW

**Comment by kgizdov** [comment]
seems to work for me in ArchLinux Gnome 3.30

**Comment by hedgepigdaniel** [comment]
Also on arch/gnome 3.30, works for me :)

**Comment by pabpas** [comment]
Fix works also on Debian testing/sid. Thanks!

**Comment by noghte** [comment]
how can I compile and replace this fixed version with the installed extension?

**Comment by marty1885** [comment]
@noghte 
```
git clone https://github.com/jimmytheneutrino/gnome-shell-extension-taskbar
cp -r gnome-shell-extension-taskbar/ ~/.local/share/gnome-shell/extensions/TaskBar@zpydr
```
Then login again.

**Comment by pabpas** [comment]
Small update after applying the fix. Now when clicking on an icon to minimize, Gnome crashes completely.

**Comment by jimmytheneutrino** [comment]
@pabpas Could you provide more details? I could not reproduce the crash.

**Comment by marty1885** [comment]
@pabpas the code in the PR works for me. No crashes for any reason.

**Comment by pabpas** [comment]
Deleted the TaskBar folder and downloaded it again. No crashes so far.

**Comment by Taijian** [comment]
Also works for me, thanks for the patch!

**Comment by jimmytheneutrino** [comment]
@zpydr Hey, it seems that people here love your work! Any chance you have in plans releasing version 58 with this (or similar) fix, some time soon?

**Comment by hashstat** [comment]
This is one of the most important extensions I use daily. After updating my Arch install it stopped working. :-(  After applying the patch for this PR, all is good again. @zpydr Please find a few minutes to review and accept this PR. Thanks!

**Comment by santicalvo** [comment]
Works for me on Debian 3.30! As @hashstat , this extension is very important to me. Thanks very much!
I hope they release soon.

**Comment by marty1885** [comment]
@jimmytheneutrino Time to fork I guess? 

Anyone here willing to maintain a fork? I might be able to update once a while. But I don't have time to add features. :(

**Comment by lsatenstein** [comment]
With Fedora and Gnome 3.3x  Taskbar crashes if we use the tweaktool to enable/disable. 
As well, if we invoke the settings and toggle any setting on or off (or try to center TB on the bottom ), a big CRASH.  
But logging out and returning restores TB under Wayland.  Alt-R does that under xorg.
repeat, its a Gnome 3.30 problem.  I use Fedora 28, and the 3.28 Gnome and with 3.28, TB has never been an issue. The left-right adjustments and toggles do not crash TB.

**Comment by marty1885** [comment]
@lsatenstein It is caused by changes introduced in Gnome 3.29.3 that is only recently merged. I'm working on a workarround. But will take time. Gnome's documents aren't that great....

**Pull request merged**
