### PR TITLE
Spanish translation for new version

### PR DESCRIPTION
**Pull request by Testoriano**

### CODE REVIEW

**Comment by zpydr** [comment]
Thanks so much Testoriano! I will merge this.

**Comment by zpydr** [comment]
Hi Tesroiano, I have created a new TaskBar.pot file, since I am planning to release a new version (56). Could you translate this to Spanish ? There is not a lot of added text. Thank you.

**Comment by zpydr** [comment]
Testoriano, sorry for misspelling your name before!

**Comment by Testoriano** [comment]
No problem for the misspelling :) 
I hope I can upload the new version in a couple of hours.

**Comment by Testoriano** [comment]
By the way, sorry for the delay.

**Pull request merged**
