### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by michal-ruzicka**
Merge against tag 44.0.

### CODE REVIEW

**Comment by zpydr** [comment]
Great, thank you!

**Comment by zpydr** [comment]
I have added a few settings and will release a new version (48) soon. It would be great if you could update the translation, I have updated the TaskBar.pot file. Looking forward to hearing from you.

**Comment by michal-ruzicka** [comment]
Thanks for the pre-release notification. The Czech translation was update, see the new pull request #98.

**Comment by zpydr** [comment]
Thank you !

**Pull request merged**
