### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by wsxy162**
Added zh_CN translation and updated it for v52.

### CODE REVIEW

**Comment by zpydr** [comment]
Merging this. Perfect, thank you very much!

**Comment by zpydr** [comment]
Hi , I have created a new TaskBar.pot file, since I am planning to release a new version (56). Could you translate this to Chinese ? There is not a lot of added text. Thank you.

**Comment by wsxy162** [comment]
[https://github.com/zpydr/gnome-shell-extension-taskbar/pull/148](Update Simplified Chinese translations)

**Comment by wsxy162** [comment]
#148

**Pull request merged**
