### PR TITLE
Vertical align, normalize and more

### PR DESCRIPTION
**Pull request by diegosanz**
I made 3 modifications:
- Vertical align for task's text (**important**): when you reduce the font size, it was aligned above, now it's aligned to middle. I.E. check it with `-4px` font size.
- Remove rounded corners in tasks: looks nicer.
- Beaufity and normalice the code.

If you don't like something, feel free to take the pieces that you like.

### CODE REVIEW

**Comment by zpydr** [comment]
Thank you so much !!! I'll probably add a setting for the rounded corners.

**Comment by lsatenstein** [comment]
All updates made to  /usr/share/gnome/shell/extensions/TaskBar@zpydr and  the new schema was installed into /usr/share/glib-2.0/schemas, with a recompile of said schema library.

Did I miss something or did someone forget to change the TaskBar version number from version 56 to perhaps 56.1 or 57.

And yes, TaskBar works just fine after the changes.

**Comment by lsatenstein** [comment]
One more tweak.  Please change   name of file taskbar.conf to match   TaskBar  suggest TaskBar.conf

**Comment by lsatenstein** [comment]
Documentation elaboration please   KeyBindings.   Current default is disabled. disabled,disabled.
I have discovered how they work, but a few words to other users would be helpful to them.

**Pull request merged**
