### PR TITLE
Tobimensch tasked grouped feature

### PR DESCRIPTION
**Pull request by tobimensch**
New feature for grouping tasks. With this feature enabled windows will be inserted in the task panel besides the last window of in the same task group.

Note:
I added another commit to this pull-request to fix bugs and make it work much better.
https://github.com/zpydr/gnome-shell-extension-taskbar/pull/104/commits/eb9c093bdc9a81b6f185110f8e1b6af99c715730

### CODE REVIEW

**Comment by zpydr** [comment]
Hi, grouping tasks is a topic that has been requested right from the start, but it takes a lot of work to implement it correctly and I have spent many hours on it, without success... yet. So thank you for this, but I found an issue; when opening multiple terminals, for example, and then closing 1 of them will close all the terminals. Unfortunately I'm very busy right now, but I'll check it for sure later on.

**Comment by tobimensch** [comment]
Hi,

can you provide me with steps to exactly reproduce this?

I opened two roxterm terminals and could close both of them individually. Also when I closed them from the taskbar, it worked individually. Which is by design.

What did you do so that all were closed at once?

Kind regards.

I've another patch for improving the preview by the way.

**Comment by zpydr** [comment]
My bad, this works perfectly! Thank you. I'll merge this, but make it a default and not an option. What do you have for the preview ?

**Comment by tobimensch** [comment]
Haha,

that's great! Love to see this merged.

I hate to hover over each individual icon in a group just so
I know which one I used to run irssi in (irc console client)
or in which nautilus instance I was in which directory.

So I combined all the previews of the same group into one
big list of previews, and you can directly click on the thumbnail
instead of the icon if you want to.

It has highlighting for the thumbnail of the icon you're hovering,
but when you go down in the list the one you're hovering with
the mouse gets highlighted instead.

I'm finding it very useful.

But it's not finished, currently it runs out of space
when there're too many windows in the same group,
and that's why I want to make it so that it expand
vertically as well as horizontally.

I'll get this done soon hopefully.

**Pull request merged**
