### PR TITLE
Czech translation update

### PR DESCRIPTION
**Pull request by michal-ruzicka**

### CODE REVIEW

**Comment by zpydr** [comment]
Thank you michal-ruzicka !

**Comment by zpydr** [comment]
Hi  michal-ruzicka, I have created a new TaskBar.pot file, since I am planning to release a new version (56). Could you translate this to Czech ? There is not a lot of added text. Thank you.

**Comment by michal-ruzicka** [comment]
Will update today, hopefully. Thanks, @zpydr.

**Comment by michal-ruzicka** [comment]
Update ready in #149.

**Pull request merged**
